var programy_lista = {
  // Mag
  'https://dealerzy.wapro.pl/erp/sprzedaz-magazyn/': 'mag',
  'https://dealerzy.wapro.pl/erp/sprzedaz-magazyn/zakres-funkcjonalny/': 'mag-zakres',
  'https://dealerzy.wapro.pl/erp/sprzedaz-magazyn/historia-zmian/': 'mag-historia',
  'https://dealerzy.wapro.pl/erp/sprzedaz-magazyn/przyklady-ekranow/': 'mag-przyklady',
  // Fakir
  'https://dealerzy.wapro.pl/erp/finanse-ksiegowosc/': 'fakir',
  'https://dealerzy.wapro.pl/erp/finanse-ksiegowosc/zakres-funkcjonalny/': 'fakir-zakres',
  'https://dealerzy.wapro.pl/erp/finanse-ksiegowosc/historia-zmian/': 'fakir-historia',
  'https://dealerzy.wapro.pl/erp/finanse-ksiegowosc/przyklady-ekranow/': 'fakir-przyklady',
  // KaPer
  'https://dealerzy.wapro.pl/erp/ksiega-podatkowa/': 'kaper',
  'https://dealerzy.wapro.pl/erp/ksiega-podatkowa/zakres-funkcjonalny/': 'kaper-zakres',
  'https://dealerzy.wapro.pl/erp/ksiega-podatkowa/historia-zmian/': 'kaper-historia',
  'https://dealerzy.wapro.pl/erp/ksiega-podatkowa/przyklady-ekranow/': 'kaper-przyklady',
  // Gang
  'https://dealerzy.wapro.pl/erp/kadry-place/': 'gang',
  'https://dealerzy.wapro.pl/erp/kadry-place/zakres-funkcjonalny/': 'gang-zakres',
  'https://dealerzy.wapro.pl/erp/kadry-place/historia-zmian/': 'gang-historia',
  'https://dealerzy.wapro.pl/erp/kadry-place/przyklady-ekranow/': 'gang-przyklady',
  // Fakturka
  'https://dealerzy.wapro.pl/erp/fakturowanie/': 'fakturka',
  'https://dealerzy.wapro.pl/erp/fakturowanie/zakres-funkcjonalny/': 'fakturka-zakres',
  'https://dealerzy.wapro.pl/erp/fakturowanie/historia-zmian/': 'fakturka-historia',
  'https://dealerzy.wapro.pl/erp/fakturowanie/przyklady-ekranow/': 'fakturka-przyklady',
  // Best
  'https://dealerzy.wapro.pl/erp/srodki-trwale/': 'best',
  'https://dealerzy.wapro.pl/erp/srodki-trwale/zakres-funkcjonalny/': 'best-zakres',
  'https://dealerzy.wapro.pl/erp/srodki-trwale/historia-zmian/': 'best-historia',
  'https://dealerzy.wapro.pl/erp/srodki-trwale/przyklady-ekranow/': 'best-przyklady',
  // B2B
  'https://dealerzy.wapro.pl/erp/b2b/': 'b2b',
  'https://dealerzy.wapro.pl/erp/b2b/zakres-funkcjonalny/': 'b2b-zakres',
  'https://dealerzy.wapro.pl/erp/b2b/funkcje/': 'b2b-funkcje',
  'https://dealerzy.wapro.pl/erp/b2b/przewagi/': 'b2b-przewagi',
  'https://dealerzy.wapro.pl/erp/b2b/uslugi/': 'b2b-uslugi',
  'https://dealerzy.wapro.pl/erp/b2b/historia-zmian/': 'b2b-historia',
  'https://dealerzy.wapro.pl/erp/b2b/przyklady-wdrozen/': 'b2b-przyklady',
  // B2C
  'https://dealerzy.wapro.pl/erp/b2c/': 'b2c',
  'https://dealerzy.wapro.pl/erp/b2c/zakres-funkcjonalny/': 'b2c-zakres',
  'https://dealerzy.wapro.pl/erp/b2c/funkcje/': 'b2c-funkcje',
  'https://dealerzy.wapro.pl/erp/b2c/przewagi/': 'b2c-przewagi',
  'https://dealerzy.wapro.pl/erp/b2c/uslugi/': 'b2c-uslugi',
  'https://dealerzy.wapro.pl/erp/b2c/historia-zmian/': 'b2c-historia',
  'https://dealerzy.wapro.pl/erp/b2c/przyklady-wdrozen/': 'b2c-przyklady',
  // JPK
  'https://dealerzy.wapro.pl/erp/wapro-jpk/': 'jpk',
  'https://dealerzy.wapro.pl/erp/wapro-jpk/zakres-funkcjonalny/': 'jpk-zakres',
  'https://dealerzy.wapro.pl/erp/wapro-jpk/historia-zmian/': 'jpk-historia',
  'https://dealerzy.wapro.pl/erp/wapro-jpk/przyklady-ekranow/': 'jpk-przyklady',
  // Online
  'https://dealerzy.wapro.pl/erp/wapro-online/': 'online',
  'https://dealerzy.wapro.pl/erp/wapro-online/mozliwosci/': 'online-mozliwosci',
  'https://dealerzy.wapro.pl/erp/wapro-online/przykladowa-kalkulacja/': 'online-kalkulacja',
  // Mobile
  'https://dealerzy.wapro.pl/erp/mobilna-firma/': 'mobile',
  'https://dealerzy.wapro.pl/erp/mobilna-firma/zakres-funkcjonalny/': 'mobile-zakres',
  'https://dealerzy.wapro.pl/erp/mobilna-firma/historia-zmian/': 'mobile-historia',
  'https://dealerzy.wapro.pl/erp/mobilna-firma/przyklady-ekranow/': 'mobile-przyklady',
  // Aukcje
  'https://dealerzy.wapro.pl/erp/aukcje/': 'aukcje',
  'https://dealerzy.wapro.pl/erp/aukcje/zakres-funkcjonalny/': 'aukcje-zakres',
  'https://dealerzy.wapro.pl/erp/aukcje/historia-zmian/': 'aukcje-historia',
  'https://dealerzy.wapro.pl/erp/aukcje/przyklady-ekranow/': 'aukcje-przyklady',
  // Analizy
  'https://dealerzy.wapro.pl/erp/analizy-wielowymiarowe/': 'analizy',
  'https://dealerzy.wapro.pl/erp/analizy-wielowymiarowe/zakres-funkcjonalny/': 'analizy-zakres',
  'https://dealerzy.wapro.pl/erp/analizy-wielowymiarowe/historia-zmian/': 'analizy-historia',
  'https://dealerzy.wapro.pl/erp/analizy-wielowymiarowe/przyklady-ekranow/': 'analizy-przyklady',
  // iBusiness
  'https://dealerzy.wapro.pl/erp/ibusiness/': 'ibusiness',
  'https://dealerzy.wapro.pl/erp/ibusiness/zakres-funkcjonalny/': 'ibusiness-zakres',
  'https://dealerzy.wapro.pl/erp/ibusiness/jak-skonfigurowac/': 'ibusiness-konfiguracja',
  // PPK
  'https://dealerzy.wapro.pl/erp/wapro-ppk-365/': 'ppk',
  'https://dealerzy.wapro.pl/erp/wapro-ppk-365/zakres-funkcjonalny/': 'ppk-zakres',
  'https://dealerzy.wapro.pl/erp/wapro-ppk-365/historia-zmian/': 'ppk-historia',
  'https://dealerzy.wapro.pl/erp/wapro-ppk-365/przyklady-ekranow/': 'ppk-przyklady',
  // Mobilny magazynier
  'https://dealerzy.wapro.pl/erp/mobilny-magazynier/': 'mobile-mag',
  'https://dealerzy.wapro.pl/erp/mobilny-magazynier/zakres-funkcjonalny/': 'mobile-mag-zakres',
  'https://dealerzy.wapro.pl/erp/mobilny-magazynier/historia-zmian/': 'mobile-mag-historia',
  'https://dealerzy.wapro.pl/erp/mobilny-magazynier/przyklady-ekranow/': 'mobile-mag-przyklady',
  // Mobilny inwentaryzator
  'https://dealerzy.wapro.pl/erp/mobilny-inwentaryzator/': 'mobile-st',
  'https://dealerzy.wapro.pl/erp/mobilny-inwentaryzator/zakres-funkcjonalny/': 'mobile-st-zakres',
  'https://dealerzy.wapro.pl/erp/mobilny-inwentaryzator/historia-zmian/': 'mobile-st-historia',
  'https://dealerzy.wapro.pl/erp/mobilny-inwentaryzator/przyklady-ekranow/': 'mobile-st-przyklady',
  // Warianty
  'https://dealerzy.wapro.pl/porownanie-wariantow/': 'porownanie-wariantow'
};

var programy_lista_bez = {
  // Mag
  '/erp/sprzedaz-magazyn/': 'mag',
  '/erp/sprzedaz-magazyn/zakres-funkcjonalny/': 'mag-zakres',
  '/erp/sprzedaz-magazyn/historia-zmian/': 'mag-historia',
  '/erp/sprzedaz-magazyn/przyklady-ekranow/': 'mag-przyklady',
  // Fakir
  '/erp/finanse-ksiegowosc/': 'fakir',
  '/erp/finanse-ksiegowosc/zakres-funkcjonalny/': 'fakir-zakres',
  '/erp/finanse-ksiegowosc/historia-zmian/': 'fakir-historia',
  '/erp/finanse-ksiegowosc/przyklady-ekranow/': 'fakir-przyklady',
  // KaPer
  '/erp/ksiega-podatkowa/': 'kaper',
  '/erp/ksiega-podatkowa/zakres-funkcjonalny/': 'kaper-zakres',
  '/erp/ksiega-podatkowa/historia-zmian/': 'kaper-historia',
  '/erp/ksiega-podatkowa/przyklady-ekranow/': 'kaper-przyklady',
  // Gang
  '/erp/kadry-place/': 'gang',
  '/erp/kadry-place/zakres-funkcjonalny/': 'gang-zakres',
  '/erp/kadry-place/historia-zmian/': 'gang-historia',
  '/erp/kadry-place/przyklady-ekranow/': 'gang-przyklady',
  // Fakturka
  '/erp/fakturowanie/': 'fakturka',
  '/erp/fakturowanie/zakres-funkcjonalny/': 'fakturka-zakres',
  '/erp/fakturowanie/historia-zmian/': 'fakturka-historia',
  '/erp/fakturowanie/przyklady-ekranow/': 'fakturka-przyklady',
  // Best
  '/erp/srodki-trwale/': 'best',
  '/erp/srodki-trwale/zakres-funkcjonalny/': 'best-zakres',
  '/erp/srodki-trwale/historia-zmian/': 'best-historia',
  '/erp/srodki-trwale/przyklady-ekranow/': 'best-przyklady',
  // B2B
  '/erp/b2b/': 'b2b',
  '/erp/b2b/zakres-funkcjonalny/': 'b2b-zakres',
  '/erp/b2b/funkcje/': 'b2b-funkcje',
  '/erp/b2b/przewagi/': 'b2b-przewagi',
  '/erp/b2b/uslugi/4/': 'b2b-uslugi',
  '/erp/b2b/historia-zmian/': 'b2b-historia',
  '/erp/b2b/przyklady-wdrozen/': 'b2b-przyklady',
  // B2C
  '/erp/b2c/': 'b2c',
  '/erp/b2c/zakres-funkcjonalny/': 'b2c-zakres',
  '/erp/b2c/funkcje/': 'b2c-funkcje',
  '/erp/b2c/przewagi/': 'b2c-przewagi',
  '/erp/b2c/uslugi/': 'b2c-uslugi',
  '/erp/b2c/historia-zmian/': 'b2c-historia',
  '/erp/b2c/przyklady-wdrozen/': 'b2c-przyklady',
  // JPK
  '/erp/wapro-jpk/': 'jpk',
  '/erp/wapro-jpk/zakres-funkcjonalny/': 'jpk-zakres',
  '/erp/wapro-jpk/historia-zmian/': 'jpk-historia',
  '/erp/wapro-jpk/przyklady-ekranow/': 'jpk-przyklady',
  // Online
  '/erp/wapro-online/': 'online',
  '/erp/wapro-online/mozliwosci/': 'online-mozliwosci',
  '/erp/wapro-online/przykladowa-kalkulacja/': 'online-kalkulacja',
  // Mobile
  '/erp/mobilna-firma/': 'mobile',
  '/erp/mobilna-firma/zakres-funkcjonalny/': 'mobile-zakres',
  '/erp/mobilna-firma/historia-zmian/': 'mobile-historia',
  '/erp/mobilna-firma/przyklady-ekranow/': 'mobile-przyklady',
  // Aukcje
  '/erp/aukcje/': 'aukcje',
  '/erp/aukcje/zakres-funkcjonalny/': 'aukcje-zakres',
  '/erp/aukcje/historia-zmian/': 'aukcje-historia',
  '/erp/aukcje/przyklady-ekranow/': 'aukcje-przyklady',
  // Analizy
  '/erp/analizy-wielowymiarowe/': 'analizy',
  '/erp/analizy-wielowymiarowe/zakres-funkcjonalny/': 'analizy-zakres',
  '/erp/analizy-wielowymiarowe/historia-zmian/': 'analizy-historia',
  '/erp/analizy-wielowymiarowe/przyklady-ekranow/': 'analizy-przyklady',
  // iBusiness
  '/erp/ibusiness/': 'ibusiness',
  '/erp/ibusiness/zakres-funkcjonalny/': 'ibusiness-zakres',
  '/erp/ibusiness/jak-skonfigurowac/': 'ibusiness-konfiguracja',
  // PPK
  '/erp/wapro-ppk-365/': 'ppk',
  '/erp/wapro-ppk-365/zakres-funkcjonalny/': 'ppk-zakres',
  '/erp/wapro-ppk-365/historia-zmian/': 'ppk-historia',
  '/erp/wapro-ppk-365/przyklady-ekranow/': 'ppk-przyklady',
  // Mobilny magazynier
  '/erp/mobilny-magazynier/': 'mobile-mag',
  '/erp/mobilny-magazynier/zakres-funkcjonalny/': 'mobile-mag-zakres',
  '/erp/mobilny-magazynier/historia-zmian/': 'mobile-mag-historia',
  '/erp/mobilny-magazynier/przyklady-ekranow/': 'mobile-mag-przyklady',
  // Mobilny inwentaryzator
  '/erp/mobilny-inwentaryzator/': 'mobile-st',
  '/erp/mobilny-inwentaryzator/zakres-funkcjonalny/': 'mobile-st-zakres',
  '/erp/mobilny-inwentaryzator/historia-zmian/': 'mobile-st-historia',
  '/erp/mobilny-inwentaryzator/przyklady-ekranow/': 'mobile-st-przyklady',
  // Warianty
  '/porownanie-wariantow/': 'porownanie-wariantow'
};